######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 16 18:35:02 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += simpleqdialog.h
FORMS += simpleqdialog.ui
SOURCES += main.cpp simpleqdialog.cpp
